nanome-ai/nanome-lib

- RemoveHydrogens.py
- nanome/_internal/_network/_commands/_serialization/_position_structures.py
- nanome/_internal/_structure/_base.py
- nanome/_internal/_structure/_io/_sdf/save.py
- nanome/_internal/_structure/_serialization/_atom_serializer.py
- nanome/_internal/_structure/_serialization/_bond_serializer.py
- nanome/_internal/_structure/_serialization/_chain_serializer.py
- nanome/_internal/_structure/_serialization/_complex_serializer.py
- nanome/_internal/_structure/_serialization/_molecule_serializer.py
- nanome/_internal/_structure/_serialization/_residue_serializer.py
- nanome/api/structure/__init__.py
- nanome/api/structure/atom.py
- nanome/api/structure/base.py
- nanome/api/structure/bond.py
- nanome/api/structure/chain.py
- nanome/api/structure/complex.py
- nanome/api/structure/molecule.py
- nanome/api/structure/residue.py
Added the api.base.Base class to be a common inheritance for all structures. Added a property wrapper for index. renamed the old index to _index. Updated all uses to use the appropriate index access level.
> NP-4135 Add Api Base

- nanome/_internal/_network/_net_instance.py
- nanome/_internal/_plugin.py
- nanome/_internal/_plugin_instance.py
- nanome/util/logs.py
Logs.debug are now only displayed if plugin is called with -v
One caveat tho: if for some reason we try to Logs.debug before the command line is parsed (which is one of the first thing to happen)
> Add verbose mode

- nanome/_internal/_network/_commands/_serialization/_create_stream.py
- nanome/_internal/_network/_commands/_serialization/_feed_stream.py
- nanome/_internal/_network/_commands/_serialization/_position_structures.py
- nanome/_internal/_network/_commands/_serialization/_request_complex_list.py
- nanome/_internal/_network/_data.py
- nanome/_internal/_network/_serialization/_context.py
- nanome/_internal/_structure/_serialization/_workspace_serializer.py
- nanome/_internal/_ui/_serialization/_layout_node_serializer.py
- nanome/_internal/_util/_serializers/_float_serializer.py
- nanome/_internal/_volumetric/_serialization/_volume_data_serializer.py
- testing/context_tests.py
- tests.py
primitive array serializers now directly write to buffer rather than repeatedly writing single primitives.
Added unit tests.
> Np 4281 optimize python serializers

- nanome/_internal/_network/_data.py
- Always expand by 1MB. This allows to allocate only once per process the expand_buffer
- Use memory view to avoid allocation with to_array
> Data class optimization

- nanome/_internal/_network/_process_network.py
- nanome/_internal/_network/_session.py
- nanome/_internal/_plugin.py
- nanome/_internal/_plugin_instance.py
- nanome/_internal/_process/_process_manager_instance.py
Prevent crash for unknown callback id
Send disconnection message to Nanome if instance crashes on linux
Close all pipes on both sides when crashing
> Fix Instance Crash on Linux

- nanome/_internal/_plugin.py
- nanome/_internal/_plugin_instance.py
- nanome/api/plugin.py
- nanome/api/plugin_instance.py
Add a simple function to set custom data to pass to plugin instances.
For instance, a plugin can read arguments, then set custom values to pass to instances, and instance can access them with self.custom_data
Or the plugin can directly pass sys.argv to its instances
> Custom Data

- nanome/_internal/_process/_bonding.py
- nanome/_internal/_structure/_io/_sdf/save.py
- test_plugins/BondingTest.py
- testing/test_assets/pdb/1tyl.pdb
(for real this time)
- fix double and triple bonds
- fix incorrect bonds on complexes loaded from PDB
PDB files can contain TER records between blocks of ATOMs, and the TER records have a serial number. This causes gaps in the atom serial numbers, which causes incorrect matching from the output of bonding to the passed in complex. To fix this, the gaps of the passed in complex are removed before matching.
> Fix bonding

- nanome/_internal/_structure/_io/_sdf/save.py
Bonds in SDFs were sometimes broken if atom `_serial`s were repeated. This fixes it by using the atom `_unique_identifier` instead of `_serial` when matching atoms.
> Fix SDF bonds

- nanome/_internal/_process/_process_manager.py
- nanome/_internal/_process/_process_manager_instance.py
- nanome/_internal/_structure/_io/_pdb/parse.py
- nanome/util/process.py
Previously Process API would not be able to read `stdout` if `stderr` was empty because `pipe.readline` blocks if pipe is empty. Solution is to split output parsing into 2 threads, one for `stdout` and one for `stderr`.
Additionally, `process.stop` was added to terminate a running process.
> Process API improvements

- nanome/_internal/_network/_commands/_callbacks/_commands_enums.py
- nanome/_internal/_network/_commands/_serialization/__init__.py
- nanome/_internal/_network/_commands/_serialization/_file/__init__.py
- nanome/_internal/_network/_commands/_serialization/_file/_export_files.py
- nanome/_internal/_network/_serialization/_serializer.py
- nanome/api/plugin_instance.py
- nanome/util/enums.py
Usage:
self.request_export(nanome.util.enums.ExportFormats.SDF, self.response, [c1, c2])
or
self.request_export(nanome.util.enums.ExportFormats.Nanome, self.response)
or
self.request_export(nanome.util.enums.ExportFormats.PDB, self.response, [index1, index2, index3])
....
the callback (self.response) receives an array. Item(s) will be binary if format is Nanome or text if pdb/sdf/mmcif/smiles
> Export api

- nanome/_internal/_network/_session.py
- nanome/_internal/_process/_process_manager.py
When plugin session ends, all processes spawned by that session with the Process API should be killed and removed from pending
> Session Process Cleanup

- nanome/_internal/_plugin_instance.py
- nanome/_internal/_plugin_instance_async.py
- nanome/api/__init__.py
- nanome/api/plugin_instance.py
- nanome/util/__init__.py
- nanome/util/asyncio.py
- test_plugins/AsyncTest.py
This PR adds the long awaited (heh) `async`/`await` support to plugins.
Notes:
- Plugin must inherit from `AsyncPluginInstance`, or manually set `_is_async = True` on the class
- Any `async` functions in a plugin must be decorated with `nanome.util.async_callback` in order to properly get executed in the asyncio event loop
- Example plugin at `test_plugins/AsyncTest.py`
- `python2` friendly - no `async`/`await` in `python2`, so measures taken to not break the whole lib
- Return values of awaitables are lists of values, for instance `request_complex_list` is `[[shallow_complex, shallow_complex, ...]]` and `request_menu_transform` is `[position, rotation, scale]`, so in the example plugin, the `shallow, = await ...` is grabbing the first item, which is the shallow complex list
TODO:
- …
> Add async/await support

- nanome/_internal/_plugin_instance.py
- nanome/_internal/_structure/_complex.py
- nanome/_internal/_structure/_helpers/_conformer_helper.py
- nanome/_internal/_structure/_helpers/_copy.py
- nanome/_internal/_structure/_io/_pdb/save.py
- nanome/_internal/_structure/_molecule.py
Needs to be tested by @nezix, I haven't tested it!
This fixes atom save constraints, that was broken by convert_to_frames (atom references weren't matching anymore). I couldn't find another solution that would have worked in 100% of cases
> Fix atom save constraints with convert_to_frames

- nanome/_internal/_structure/_atom.py
- nanome/_internal/_structure/_serialization/_atom_serializer.py
- nanome/api/structure/atom.py
Replaced atom_rendering with a bit manipulation of the display_mode.
I'm not exposing the display_mode yet because we don't have a proper bitflag implementation. But this at least will prevent the plugin from wiping the flag used in nanome core during quick prep.
> added in the display_mode int flag.

- nanome/_internal/_plugin.py
- nanome/api/plugin.py
- Move command line arg parsing into `Plugin`, since they are set by the user.
- Use argparse library instead of manually looping through sys.argv
- General spacing and formatting fixes.
> Argparser refactor

- nanome/_internal/_process/_process_manager_instance.py
Process API had a weird race condition with processes that used both asyncio and `on_done`.
Case in point: bonding (also dssp)
- When bonding is run on multiple structures, it reuses the `Process` object for multiple runs of the bonding process.
- To do this, it sets up the input and calls `start` on the `Process` after the previous run's `on_done`.
- Problem was, for async plugins, `start` creates a new `Future`, but the result of the `Future` was being set _after_ `on_done`.
So, bonding would run once, create a `Future`, finish and call `on_done` which then started a new process, _then_ attempt to set the first run's `Future` result which at this point was now a new `Future` from the second run. Not good. But now fixed. :D
> Fix async process race condition

- nanome/_internal/_plugin_instance_async.py
- nanome/_internal/_shapes/_shape.py
- nanome/api/shapes/shape.py
quick debrief on the cause:
- asyncio futures can only have a single result
- when we asyncified upload_multiple, there were 2 return values (indices and results), so we had to pack/unpack them for the future and callback
- Code was probably just copied without knowing what the *args was for, and it wasn't needed for destroy since there's only one arg (results)
- additionally, shape.py destroy_multiple wasn't returning the future from calling _destroy_multiple
> Fix destroy_multiple bug

- nanome/setup_config.py
After logging refactor, when Logs.message is called outside of running plugin, there are no handlers to display log messages.
Add basic logger and handler so messages are shown in the console
> Fix bug in printing for nanome-setup-plugins function

- nanome/_internal/_network/_net_instance.py
- nanome/_internal/_plugin.py
- nanome/_internal/_plugin_instance.py
- nanome/_internal/logs.py
- nanome/api/plugin.py
- testing/plugin_tests.py
Fix issue where setting the --verbose plugin flag caused remote logging to crash on NTS.
- Set process start method to spawn, so we should now have consistent behavior between Linux and Windows.
- Remove verbose arg from PluginInstance init, because it wasn't used
- Make console handler first log handler, so if remote call fails we can still see the output in the console
- Tidy up exception logging in NetInstance
- Fix bug where setting --remote-logging as anything made it true (Now accepts false values)
> Verbose logs fix

- nanome/_internal/_plugin.py
set_start_method has to be called before process Queues are instantiated.
Tested in Linux, Windows, and Docker. (Pending Mac approval)
Also make session register an info log, as that is an important message to monitor
> Set start method fix

- .github/workflows/regression-tests.yml
- nanome/api/plugin_instance.py
Run unittests for plugins with latest lib changes, so we catch more errors before they get merged.
Also move setting PluginInstance._instance back to __init__, so that we don't have to do this for every unittest
https://github.com/nanome-ai/plugin-chemical-interactions/blob/master/tests/test_cases.py#L36
We now ensure that __init__ is run from _setup, so this is ok
> add regression test github action

- nanome/_internal/_structure/_chain.py
- nanome/_internal/_structure/_complex.py
- nanome/_internal/_structure/_molecule.py
- nanome/_internal/_structure/_residue.py
- nanome/_internal/_structure/_workspace.py
Previously, if you call `residue.remove_bond` with a `Bond` that's not in the `Residue`, it would raise an exception. This PR makes it only attempt removing if the item is actually in the list.
> Fix remove errors

- nanome/_internal/_network/_process_network.py
- nanome/_internal/_plugin.py
- nanome/_internal/_plugin_instance.py
- nanome/api/plugin_instance.py
- testing/plugin_instance_tests.py
- rename _launch_plugin to run_plugin_instance
- Create ProcessNetwork before PluginInstance._setup, which reduces the parameter count
- Move __init__s to the top of the class
- Add some docstrings
- Reduce some line-lengths
> _Internal  Plugin refactor

- nanome/util/asyncio.py
The re-enables the ability to get a return value from `await`ing a `@async_callback` wrapped `async` method
> Add return to async_callback exception_wrapper

- nanome/_internal/_macro/_macro.py
- nanome/_internal/_network/__init__.py
- nanome/_internal/_network/_process_network.py
- nanome/_internal/_plugin.py
- nanome/_internal/_plugin_instance.py
- nanome/_internal/_process/__init__.py
- nanome/_internal/_process/_process_entry.py
- nanome/_internal/_process/_process_manager.py
- nanome/_internal/_process/_process_manager_instance.py
- nanome/_internal/_room.py
- nanome/_internal/_shapes/_shape.py
- nanome/_internal/_ui/_button.py
- nanome/_internal/_ui/_image.py
- nanome/api/plugin.py
- nanome/api/structure/client/workspace_client.py
- nanome/api/structure/complex.py
- nanome/api/structure/molecule.py
- nanome/util/process.py
- testing/plugin_tests.py
- Remove underscores from classes and attributes that are utilized outside of class itself
- Rename _ProcessNetwork to NetworkProcess. Emphasizes that it is part of networking code, not Process API
- Move __inits__ to top of classes
> Mostly Cosmetic Process refactor

- .github/workflows/publish.yml
- .github/workflows/unittests.yml
- nanome/util/color.py
- testing/color_tests.py
`Color.to_string_hex` was not exactly useful. There were no leading zeroes, and it was prefixed with `0x`.
A color like cyan would output as `0xffff` (0 R, 0 G, 255 B, 255 A).
This PR outputs in hex RGBA with a `#` prefix, so cyan = `#0000ffff`.
> Make Color.hex output like #ffffffff

- testing/logging_tests.py
* Tests for util.Logs that actually validate output
*  use __name__ instead of hardcoding "logging_tests", which makes tests more robust
> Split out util.Log tests into their own testcase

- nanome/api/schemas/structure_schemas.py
- testing/test_assets/serialized_data/benzene_workspace.json
- testing/test_plugins/SerializeWorkspace.py
- testing/unit/test_schemas.py
- Use StructureSchema to dynamically determine which type of structure to create.
- Add tests to validate StructureSchema
- Add SerializeWorkspace test plugin to generate workspace schemas
> Structure schema fix

- nanome/_internal/_structure/_complex.py
- nanome/_internal/_structure/_io/_sdf/save.py
* Continue bond loop if atoms not found
* Also delete unused double underscore function
Fixes Chemical Properties error in Graylog message graylog_0/7f205280-2231-11ed-9c53-0242ac120002
> Fix SDF save bug

- nanome/_internal/_structure/_io/_sdf/parse.py
SDF associated data is stored in the format:
```
> <Property>
Value
```
There was a bug in the SDF parser regex usage where it was grabbing the full `> <Property>` as the property name instead of `Property`. This PR fixes that.
> Fix SDF parsing associated data

- nanome/_internal/_network/_commands/_callbacks/_interrupt_stream.py
- nanome/_internal/_network/_session.py
- nanome/_internal/_plugin_instance_async.py
- "Plugin encountered an Error" not a helpful log
- Prevent errors being spammed when stream interrupt fails.
> Fix logging bugs/ remove unused import

- nanome/_internal/process/dssp.py
- nanome/util/config.py
```
Traceback (most recent call last):
File "/app/run.py", line 1, in <module>
from plugin import StructurePrep
File "/app/plugin/StructurePrep.py", line 1, in <module>
import nanome
File "/opt/conda/lib/python3.9/site-packages/nanome/__init__.py", line 3, in <module>
from .api import *
File "/opt/conda/lib/python3.9/site-packages/nanome/api/__init__.py", line 2, in <module>
from .room import Room
File "/opt/conda/lib/python3.9/site-packages/nanome/api/room.py", line 2, in <module>
from nanome._internal._room import _Room
File "/opt/conda/lib/python3.9/site-packages/nanome/_internal/__init__.py", line 12, in <module>
from ._plugin_instance import _PluginInstance  # noqa F401
File "/opt/conda/lib/python3.9/site-packages/nanome/_internal/_plugin_instance.py", line 4, in <module>
from …
```
> add back chmod for dssp, wrap in try/except

- nanome/api/schemas/structure_schemas.py
- testing/test_plugins/SchemaBondTest.py
Fixes issue where bonds were lost after serializing/deserializing complex
Issues:
* Atom was missing unique_identifier field.
* atom1 and atom2 in the BondSchema was only saving index, in an effort to reduce payload size. However, that minimal atom was being saved as the primary atom data for the payload here.
https://github.com/nanome-ai/nanome-lib/blob/master/nanome/api/structure/serializers.py#L189
So when the payload was serialized, all the important data was missing.
> Schema bond fix
