nanome-ai/nanome-lib

LoadFile.py, nanome/_internal/_network/_commands/_callbacks/__init__.py, nanome/_internal/_network/_commands/_callbacks/_commands_enums.py, nanome/_internal/_network/_commands/_callbacks/_position_structures_done.py, nanome/_internal/_network/_commands/_serialization/__init__.py, nanome/_internal/_network/_commands/_serialization/_position_structures_done.py, nanome/_internal/_network/_serialization/_serializer.py, nanome/api/plugin_instance.py
Added support for callbacks to position commands.
=> Np 4109 position api callbacks

nanome/_internal/_plugin.py, nanome/api/plugin.py
Goes from:
`if __name__ == "__main__":
plugin = nanome.Plugin.start("Ligand Focus", "On-click focus on a ligand and its binding site", "Utilities", False)
plugin.set_plugin_class(LigandFocus)
plugin.run('127.0.0.1', 8888)`
To:
`nanome.Plugin.setup("Ligand Focus", "On-click focus on a ligand and its binding site", "Utilities", False, LigandFocus, '127.0.0.1', 8888)`
=> Implement a one line plugin setup

nanome/_internal/_structure/_serialization/_complex_serializer.py, nanome/util/quaternion.py, nanome/util/vector3.py
Change coordinate system for complex position and rotation
=> Fix complexes coordinates

nanome/_internal/_network/_commands/_serialization/_button_callback.py, nanome/_internal/_network/_commands/_serialization/_image_callback.py, nanome/_internal/_network/_commands/_serialization/_slider_callback.py, nanome/_internal/_network/_commands/_serialization/_text_input_callback.py, nanome/_internal/_network/_process_network.py, nanome/_internal/_network/_serialization/_context.py, nanome/_internal/_network/_serialization/_serializer.py, nanome/_internal/_ui/_serialization/_button_serializer.py, nanome/_internal/_ui/_serialization/_image_serializer.py, nanome/_internal/_ui/_serialization/_label_serializer.py, nanome/_internal/_ui/_serialization/_layout_node_serializer.py, nanome/_internal/_ui/_serialization/_loading_bar_serializer.py, nanome/_internal/_ui/_serialization/_mesh_serializer.py, nanome/_internal/_ui/_serialization/_slider_serializer.py, nanome/_internal/_ui/_serialization/_text_input_serializer.py, nanome/_internal/_ui/_serialization/_ui_list_serializer.py, testing/atom_tests.py, testing/utilities.py
added plugin id to context
fixed version number in serializer unit tests
used plugin id in layout_node_serializer to resolve layout_id_collisions
=> content_id_collision_hotfix

nanome/_internal/_network/_commands/_callbacks/_menu.py, nanome/_internal/_plugin_instance.py, nanome/_internal/_ui/_io/_layout_node_json.py, nanome/_internal/_ui/_layout_node.py, nanome/api/ui/layout_node.py, test_plugins/UIPlugin.py
moved layoutnode api to api class
removed catching of IOError and BrokenPipeError
=> various polishing

nanome/_internal/_plugin.py
=> Add an argument to rename a plugin temporarily

nanome/api/plugin_instance.py, nanome/util/config.py, setup_config.py
Add a general plugin files path with a getter in plugin_instance
Configurable with the nanome-setup-plugins utility
=> Files Path

nanome/_internal/_network/_commands/_callbacks/__init__.py, nanome/_internal/_network/_commands/_callbacks/_commands_enums.py, nanome/_internal/_network/_commands/_callbacks/_presenter_change.py, nanome/_internal/_network/_commands/_callbacks/_receive_presenter_info.py, nanome/_internal/_network/_commands/_serialization/__init__.py, nanome/_internal/_network/_commands/_serialization/_get_presenter_info.py, nanome/_internal/_network/_commands/_serialization/_get_presenter_info_response.py, nanome/_internal/_network/_commands/_serialization/_presenter_change.py, nanome/_internal/_network/_process_network.py, nanome/_internal/_network/_serialization/_serializer.py, nanome/api/__init__.py, nanome/api/plugin_instance.py, nanome/api/user/__init__.py, nanome/api/user/presenter_info.py, test_plugins/SandBox.py
Add an API to request account info about presenter
Add on_presenter_change API
=> Presenter API

nanome/_internal/_process/_bonding.py, nanome/_internal/_structure/_helpers/_conformer_helper.py
`add_bonds` was broken on conformers. This fixes that.
=> Fix bonding

nanome/_internal/_process/_bonding.py, nanome/_internal/_process/_dssp.py
Previous fix to bonding for conformers broke it for frames, and had a bonding issue.
This PR fixes that. And also fixes dssp. So both dssp and bonding should work on complexes in frame mode as well as conformer mode.
=> Conformer fixes

nanome/_internal/_util/_serializers/_string_serializer.py, test_plugins/SandBox.py
=> Fix encoding

nanome/api/structure/complex.py
Add `get_all_selected` and `set_all_selected` to complex to return / set if all atoms in a complex are selected
=> Complex all_selected methods

nanome/_internal/_process/_dssp.py
This PR adds recognition for more DSSP symbols
=> Add DSSP symbols

nanome/_internal/_structure/_atom.py, nanome/_internal/_structure/_serialization/_atom_serializer.py
Added _atom_type field to _atom.py and proper serialization and deserialization to _atom_serializer.py and incremented the version number from 3 to 4.
=> [QA] NP-4878_AtomTypePluginSupport

nanome/_internal/_structure/_atom.py, nanome/_internal/_structure/_serialization/_atom_serializer.py, nanome/api/structure/atom.py
Add partial charge serialization.
Add API for formal and partial charges.
=> Atom partial charges serialization

nanome/_internal/_ui/_io/_text_input_json.py, nanome/_internal/_ui/_serialization/_text_input_serializer.py, nanome/_internal/_ui/_text_input.py, nanome/api/ui/text_input.py, test_plugins/UIPlugin.py
Added more options to the text input API.
=> Text input api

nanome/_internal/_structure/_atom.py, nanome/_internal/_structure/_serialization/_atom_serializer.py, test_plugins/AtomTypingTest.py
nanome-core pr: https://github.com/nanome-ai/nanome-core/pull/103
=> generic atom typing

nanome/api/plugin_instance.py, nanome/util/enums.py
This is where I would look for this
=> PluginListButtonType in enums

nanome/_internal/_integration/_serialization/_generate_molecule_image.py, test_plugins/GenerateMoleculeImageIntegration.py
https://github.com/nanome-ai/nanome-core/pull/320
=> added the resolution tuple to the callback

nanome/_internal/_macro/_macro.py, nanome/_internal/_plugin_instance.py, nanome/_internal/_process/_bonding.py, nanome/_internal/_process/_dssp.py, nanome/api/files.py, nanome/api/macro/macro.py, nanome/api/plugin_instance.py, nanome/api/structure/client/workspace_client.py, test_plugins/FileExplorer.py
Add `async` ability to:
- Macro API
- Files API
- `add_bonds`
- `add_dssp`
- `compute_hbonds`
=> Async Updates

nanome/_internal/_plugin.py
When plugin disconnects from NTS, try again 1 second later, then 2, then 4, then 8... to a max of 20s if NTS continues to not respond
=> Reconnect Exponential Backoff

nanome/_internal/_network/_commands/_serialization/_shapes/_set_shape.py
Adapt set shape serializer to array and fix backward compat
=> Fix batch shape serializer

nanome/_internal/_network/_commands/_serialization/_shapes/_delete_shape.py, nanome/_internal/_network/_commands/_serialization/_shapes/_set_shape.py, nanome/_internal/_shapes/_shape.py, nanome/api/shapes/shape.py
https://nanome.atlassian.net/browse/NX-766?atlOrigin=eyJpIjoiMDc1NGViYWU0ZDEyNGNiZDkzMjQ2N2UxMjA3NWI5NDEiLCJwIjoiaiJ9
=> Nx 766 batch shapes fallback

nanome/plugin_init.py, plugin-template/.devcontainer/Dockerfile, plugin-template/.devcontainer/devcontainer.json, plugin-template/.gitignore, plugin-template/.vscode/tasks.json, plugin-template/nanome_plugin/Plugin.py
- Use argparse in nanome-plugin-init
- Fix Python Paths in default devcontainer folder
- Add autopep8 task to default .vscode settings
=> devcontainer updates/ plugin_init argparser/ 

nanome/_internal/_network/_commands/_serialization/_open_url.py, nanome/api/plugin_instance.py
https://github.com/nanome-ai/nanome-core/pull/694
=> Basic VR Browser Support

doc/source/shapes.rst, doc/source/streams.rst, doc/source/workspace.rst
=> Position Math docs

.github/workflows/unittests.yml, nanome/_internal/_network/_session.py, nanome/_internal/_plugin.py, nanome/_internal/_plugin_instance.py, nanome/_internal/_process/_process_manager_instance.py, nanome/_internal/_util/_proc_data.py, nanome/_internal/logs.py, nanome/util/logs.py, requirements.txt, setup.py, test_plugins/UIPlugin.py
- Use new PipeHandler to pipe all logs from child processes into main process
=> Windows logging

nanome/_internal/_plugin.py
=> Temp comment out multiprocessing start method

nanome/__init__.py, nanome/_internal/_plugin.py, nanome/api/plugin.py, nanome/setup_config.py, nanome/util/config.py, testing/plugin_tests.py
Enable all settings to be set using env vars.
Set priorities for where settings originate from ( Cli > Env var > Config file)
=> Refactor utils.config

nanome/api/plugin_instance.py
- Set PluginInstance._instance in _setup() override.
- Make sure __init__ is called manually if child classes of PluginInstance don't call super
=> Fix plugininstance._instance

nanome/_internal/_integration/_serialization/__init__.py, nanome/_internal/_integration/_serialization/_export_smiles.py, nanome/_internal/_integration/_serialization/_import_smiles.py, nanome/_internal/_network/_commands/_callbacks/_commands_enums.py, nanome/_internal/_network/_commands/_serialization/_integration.py, nanome/api/integration/integration.py, nanome/util/enums.py
`import_smiles` and `export_smiles`
=> SMILES integrations

nanome/_internal/_network/_process_network.py, nanome/_internal/_plugin.py, nanome/_internal/_plugin_instance.py, nanome/api/plugin_instance.py, testing/plugin_instance_tests.py
This reverts commit a1f8a4c6ca3473639178fc4dbdb6b5b2220fd274.
=> Revert "_Internal  Plugin refactor (#282)"

.github/workflows/unittests.yml, nanome/_internal/_process/_process_manager.py, nanome/util/process.py, test_plugins/AsyncProcessTest.py, testing/logging_tests.py
- Will allow us  to more easily differentiate multiple processes used in one plugin.
- Log warnings for Processes that don't return a 0 exit code
=> Add label attribute to Processes

nanome/_internal/_process/_bonding.py, nanome/_internal/_process/_dssp.py, nanome/_internal/_process/_process_manager.py, nanome/util/process.py
- Skip dssp on molecules that only contain hetatoms
- Add labels to bonding and dssp processes
- Update process complete log message
- Fix asyncio errors when no bins for bonding / dssp
- Remove debug log for dssp
=> Bonding and DSSP updates

nanome/_internal/_network/_process_network.py, nanome/_internal/_plugin.py, nanome/_internal/_plugin_instance.py, nanome/_internal/_process/_process_manager.py, nanome/api/plugin_instance.py, testing/plugin_instance_tests.py
This reverts commit https://github.com/nanome-ai/nanome-lib/commit/3f74fb97f2b164256872ff163b5d9d64e5913345.
=> Revert "Revert "_Internal Plugin refactor (#282)" (#289)"

nanome/_internal/_network/_process_network.py, nanome/_internal/_network/_session.py, nanome/_internal/_plugin.py, nanome/_internal/_plugin_instance.py, nanome/_internal/_process/_process_manager_instance.py, nanome/api/plugin_instance.py, testing/unit/test_plugin_instance.py
potentially fixes EOFError that keeps popping up
=> Change ProcessManager pipe to queues

nanome/_internal/logs.py
This reverts commit d137d1e71eba093c882ec01c150be7a98f8c2d84.
=> Revert "Add plugin version to graylog logs (#317)"

.github/workflows/unittests.yml, nanome/_internal/_plugin_instance.py, nanome/_internal/_plugin_instance_async.py
- Hopefully reduces CPU creep for deployed plugins
=> add 12 hour timeout for unclosed Plugin Sessions

nanome/util/enums.py
This PR is linked to Core PR: https://github.com/nanome-ai/nanome-core/pull/989
=> Add Bfactor AlphaFold color scheme

nanome/api/schemas/shapes_schema.py, setup.py, testing/unit/test_schemas.py
Bump marshmallow version to 3.18.0
=> Add missing schema for Line Shape

.github/workflows/unittests.yml, README.md, doc/source/conf.py, doc/source/file.rst, doc/source/plugins.rst, doc/source/ui.rst
* Fix relative imports that were causing issues with build
* Fix test plugin imports to documentation
* Use AsyncPluginInstance in first example plugins
* Fix python-version for unittest github action
=> Docs fixes

.github/workflows/linter.yml, .github/workflows/publish.yml, .github/workflows/regression-tests.yml, .github/workflows/unittests.yml, testing/unit/test_atoms.py
- Remove custom pattern from unittest call
- Add test for fill-atom-table. Increases code coverage for that file
- Update checkout actions to v3 to fix Node16 warnings
=> fix unittest github action

nanome/api/schemas/api_definitions.py
Defines expected parameters and output Schemas for key API functions.
=> Add api_definitions.py file

readthedocs.yaml, setup.py
- Also remove marshmallow from beta extra requirements, since its no longer used there
=> Make sure extra requirements get installed during readthedocs build

nanome/beta/nanome_sdk/plugin_server.py
This should fix empty error messages coming from Cryo-EM
=> Get better error messages from plugin_server.py exceptions
